# -*- coding: utf-8 -*-
"""SumaDigitosRecursivo.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YGksQVtTOtUd9dcbwwV1PEEJUIUTh9S
"""

class SumaDigitos:
    """
    Clase que suma los dígitos de un número entero usando recursividad.
    """

    def __init__(self, numero):
        """
        Inicializa el número a procesar.
        :param numero: int - Número entero positivo.
        """
        self.numero = numero

    def sumar_digitos(self, n=None):
        """
        Método recursivo que suma los dígitos del número.
        :param n: int - Valor usado en la recursión (opcional).
        :return: int - Suma de los dígitos.
        """
        if n is None:
            n = self.numero

        # Caso base
        if n == 0:
            return 0

        # Paso recursivo
        return n % 10 + self.sumar_digitos(n // 10)

    def mostrar_resultado(self):
        """
        Muestra el resultado de la suma de los dígitos.
        """
        resultado = self.sumar_digitos()
        print("\n==============================")
        print("  Suma Recursiva de Dígitos ")
        print("==============================")
        print(f"Número: {self.numero}")
        print(f"Suma de dígitos: {resultado}")
        print("==============================\n")


# ============================================
# EJECUCIÓN DEL PROGRAMA
# ============================================
if __name__ == "__main__":
    print("=== Suma Recursiva de los Dígitos de un Número ===")

    try:
        numero = int(input("Ingrese un número entero positivo: "))
        if numero < 0:
            print(" Error: solo se permiten números positivos.")
        else:
            suma = SumaDigitos(numero)
            suma.mostrar_resultado()
    except ValueError:
        print(" Error: debe ingresar un número entero válido.")